language: r
sudo: false
cache: packages

branches:
  except:
    - /^*-v[0-9]/

r_packages:
  - covr
  - drat
  - devtools

before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

 # Build and check package
script:
  - R CMD build .
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --as-cran
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && perl compare_versions --tag && bash deploy.sh && curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/broadsea-methodslibrary/trigger/f0b51cec-4027-4781-9383-4b38b42dd4f5/
  - Rscript -e 'library(covr);codecov()'
  
notifications:
  recipients:
    - alondhe2@its.jnj.com
    - mblacke@its.jnj.com
    - fdefalco@its.jnj.com
  email:
    on_success: change
    on_failure: change
